package codegen;

import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Map.Entry;

import codegen.modelobjects.DTO;
import codegen.modelobjects.SMDDescriptor;
import codegen.modelobjects.Service;

import com.google.gson.JsonIOException;
import com.google.gson.JsonSyntaxException;

public class CodeGenMain {
	public static void main(String[] args) throws JsonIOException, JsonSyntaxException, MalformedURLException,
			IOException {
		SchemaReader rdr = new SchemaReader("http://ciapipreprod.cityindextest9.co.uk/TradingApi/schema",
				"http://ciapipreprod.cityindextest9.co.uk/TradingApi/smd");

		rdr.createPackage("autoGenerated", "/home/justin/workspace/CIAPI.Java/src/JsonClient/src/main/java/autoGenerated");
	}
}
